aws_region           = "us-east-1"
project_name         = "strapi-app"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidr   = "10.0.1.0/24"
public_subnet_2_cidr = "10.0.3.0/24"
private_subnet_cidr  = "10.0.2.0/24"
public_key_path     = "~/.ssh/my-strapi-key.pub"
app_instance_type   = "t3.small"
bastion_instance_type = "t3.micro"
my_ip_cidr          = "0.0.0.0/0"
github_repo_https   = "https://github.com/shoaibakhtargithub/my-strapi-app"
github_repo_branch  = "master"
app_dir             = "my-strapi-app"

